language: generic 

sudo: required
services: 
    - docker

before_install:
    - docker build -f Dockerfile.dev -t plpetkov/docker-react .

script: 
    - docker run -e CI=true plpetkov/docker-react npm run test